// ConsoleColors.cpp : Defines the functions for the static library.
//

#include "pch.h"
#include "framework.h"
#include"console_colors.h"
#pragma region Colors definitions

WORD Colors::WHITE = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE |

FOREGROUND_INTENSITY;

WORD Colors::BLACK = 0;

WORD Colors::GREY = FOREGROUND_INTENSITY;

WORD Colors::LIGHTGRAY = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE;

WORD Colors::BLUE = FOREGROUND_BLUE;

WORD Colors::GREEN = FOREGROUND_GREEN;

WORD Colors::CYAN = FOREGROUND_GREEN | FOREGROUND_BLUE;

WORD Colors::RED = FOREGROUND_RED;

WORD Colors::PURPLE = FOREGROUND_RED | FOREGROUND_BLUE;

WORD Colors::LIGHTBLUE = FOREGROUND_BLUE | FOREGROUND_INTENSITY;

WORD  Colors::LIGHTGREEN = FOREGROUND_GREEN | FOREGROUND_INTENSITY;

WORD Colors::LIGHTCYAN = FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY;

WORD Colors::LIGHTRED = FOREGROUND_RED | FOREGROUND_INTENSITY;

WORD LIGHTPURPLE = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY;

WORD Colors::YELLOW = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY;

WORD Colors::ORANGE = FOREGROUND_RED | FOREGROUND_GREEN;

/// <summary>
/// Background colors
/// </summary>

WORD Colors::WHITEBack = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE |

BACKGROUND_INTENSITY;

WORD Colors::BLACKBack = 0;

WORD Colors::GREYBack = BACKGROUND_INTENSITY;

WORD Colors::LIGHTGRAYBack = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE;

WORD Colors::BLUEBack = BACKGROUND_BLUE;

WORD Colors::GREENBack = BACKGROUND_GREEN;

WORD Colors::CYANBack = BACKGROUND_GREEN | BACKGROUND_BLUE;

WORD Colors::REDBack = BACKGROUND_RED;

WORD Colors::PURPLEBack = BACKGROUND_RED | BACKGROUND_BLUE;

WORD Colors::LIGHTBLUEBack = BACKGROUND_BLUE | BACKGROUND_INTENSITY;

WORD Colors::LIGHTGREENBack = BACKGROUND_GREEN | BACKGROUND_INTENSITY;

WORD Colors::LIGHTCYANBack = BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY;

WORD Colors::LIGHTREDBack = BACKGROUND_RED | BACKGROUND_INTENSITY;

WORD Colors::LIGHTPURPLEBack = BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY;

WORD Colors::YELLOWBack = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_INTENSITY;

WORD Colors::ORANGEBack = BACKGROUND_RED | BACKGROUND_GREEN;

#pragma endregion
